# git source
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '15.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'SimplePlayer.TT' do

  # TTSDK-Player
  pod 'TTSDKFramework', '1.48.1.9-premium', :subspecs => ['Player-SR']

end

# xcode14 code sign
post_install do |installer|
  [installer.generated_projects, installer.pods_project]
  .flatten.map{ |p| p.targets}
  .flatten.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["CODE_SIGN_IDENTITY"] = "-"
        config.build_settings["CODE_SIGN_ENTITLEMENTS"] = "-"
        config.build_settings["CODE_SIGNING_ALLOWED"] = "NO"
        config.build_settings["CODE_SIGNING_REQUIRED"] = "NO"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
